### Polynomial
In mathematics, a polynomial is an expression consisting of variables (also called indeterminates) and coefficients, that involves only the operations of addition, subtraction, multiplication, and non-negative integer exponents of variables. An example of a polynomial of a single indeterminate, x, is **$x^2 − 4x + 7$**. An example in three variables is **$x^3 + 2xyz^2 − yz + 1$**.

Polynomials appear in many areas of mathematics and science. For example, they are used to form polynomial equations, which encode a wide range of problems, from elementary word problems to complicated scientific problems; they are used to define polynomial functions, which appear in settings ranging from basic chemistry and physics to economics and social science; they are used in calculus and numerical analysis to approximate other functions. In advanced mathematics, polynomials are used to construct polynomial rings and algebraic varieties, central concepts in algebra and algebraic geometry.

In [21]:
import numpy as np
from numpy.polynomial.polynomial import polyval

#### $3x^2+2X+1$

In [20]:
polyval(1, [1,2,3])

6.0

#### $x^2+2x+3$

In [18]:
polyval(2, [3,2,1])

11.0

In [27]:
polyval(2, [1,2,3])

17.0

$3x^2+2x+1$

In [24]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [29]:
polyval(a,[1,2,3])

array([[ 1.,  6.],
       [17., 34.]])

In [53]:
P = np.arange(4).reshape(2,2)    # Equation by using Axis = Columns
P

array([[0, 1],
       [2, 3]])

**Eq1:**$2x$

**Eq2:**$3x+1$

In [50]:
polyval([1,2],P,tensor=True)

array([[2., 4.],
       [4., 7.]])

In [35]:
polyval([1,2],P,tensor=False)

array([2., 7.])

In [54]:
First_Degree = np.poly1d([1,2,3])
print(First_Degree)

   2
1 x + 2 x + 3


In [56]:
First_Degree.coefficients

array([1, 2, 3])

In [58]:
First_Degree.coef

array([1, 2, 3])

In [59]:
First_Degree.coeffs

array([1, 2, 3])

In [41]:
First_Degree.roots

array([-1.+1.41421356j, -1.-1.41421356j])

In [44]:
First_Degree.order

2

In [68]:
c1 = np.poly1d([1,2,3])
c2 = np.poly1d([3,2,1])
sum_ = np.polyadd(c1,c2); #sum
sum_

poly1d([4, 4, 4])

In [73]:
print(c1)
print(c2)

   2
1 x + 2 x + 3
   2
3 x + 2 x + 1


In [75]:
np.roots(sum_)

array([-0.5+0.8660254j, -0.5-0.8660254j])

In [76]:
from numpy.polynomial import polynomial as P
Sum = P.polyadd(c1,c2); #sum
Sum

array([4., 4., 4.])

In [78]:
P.polyval(2, Sum) # 4 + 4(2) + 4(2**2)

28.0

In [79]:
P.polysub(c1,c2)

array([-2.,  0.,  2.])

In [80]:
P.polyroots(c1)

array([-0.33333333-0.47140452j, -0.33333333+0.47140452j])

In [81]:
P.polydiv(c1,c2)

(array([3.]), array([-8., -4.]))

In [82]:
P.polymul(c1,c2)

array([ 3.,  8., 14.,  8.,  3.])

In [83]:
P.polypow(c1,2)

array([ 1.,  4., 10., 12.,  9.])