### The Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

#### ndarray.ndim

the number of axes (dimensions) of the array.

#### ndarray.shape

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

#### ndarray.size

the total number of elements of the array. This is equal to the product of the elements of shape.

#### ndarray.dtype

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

#### ndarray.itemsize

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

#### ndarray.data

the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [2]:
import numpy as np

In [ ]:
b = np.array([6, 7, 8])
a = np.arange(15).reshape(3, 5)
print(a.shape,"Shape of 'a' array\n")
print(a.ndim,"Dimension of an array\n")
print(a.dtype.name,"Data type\n ")
print(a.itemsize,"Find the iteamsize in array\n ")
print(a.size,"size oF an array\n")
print(type(a))
print(type(b),b)

### Array Creation
There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [ ]:
import numpy as np
a = np.array([2,3,4])
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b.dtype)

A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [ ]:
#a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)])
b.size
b.shape

The type of the array can also be explicitly specified at creation time:

In [ ]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [ ]:
x = np.zeros((3,4))
x

In [ ]:
x = np.ones( (2,3,4), dtype=np.int16 )
x

In [ ]:
d = np.empty( (2,3) )
d

In [ ]:
e = np.arange( 10, 30, 5 )
print(e)
f = np.arange( 0, 2, 0.3 ) 
print(f)

In [ ]:
from numpy import pi
g = np.linspace( 0, 2, 9) 
print(g)

In [ ]:
xy = np.linspace( 0, 2*pi, 10) 
print(xy,"xy Variable has linspace is\n")
f = np.sin(xy)
print(xy,"linspace with pi\n",f,"sin on xy")

### Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

the last axis is printed from left to right,
the second-to-last is printed from top to bottom,
the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [ ]:
a = np.arange(6)                         # 1d array
print(a,'1d array\n')

b = np.arange(12).reshape(4,3)           # 2d array
print(b,"2d array\n")

c = np.arange(24).reshape(2,3,4)         # 3d array
print(c,"3d array\n")

If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [ ]:
print(np.arange(10000),"\nPrinting all range of values from 0 to 10000")


In [ ]:
print(np.arange(10000).reshape(100,100),"\nPrinting all range of values from 0 to 10000")

To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

### Basic Operations
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
aa = np.array( [20,30,40,50] )
bc = np.arange( 4 )
#print(aa,bc)
print(aa-bc,"Sub of Two arrays\n")
print(np.subtract(aa,bc),"Sub of Two arrays\n")
print(np.add(aa,bc),"Addation of two arrays\n")
print(aa+bc,"\n")
print(np.multiply(aa,bc),"Mul of two arrays\n")
print(aa*bc,"\n")

In [ ]:
print(np.divide(aa,bc),"aa number divide with bc numbers")
print(aa/bc,"div\n")

In [ ]:
print(np.divmod(aa,bc),"Divmode")

In [ ]:
bc**2

In [ ]:
10*np.sin(aa)

In [ ]:
print(aa<35,"Comp")
print(aa>35,"Comp")
print(aa==bc,"comp\n")

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [ ]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
print(A * B ,"# elementwise product\n")
print(A @ B ,"# matrix product\n")
print(A.dot(B),"# another matrix product")

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [ ]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
b += a
print("Assignement operaters Mul\n",a)
print("Assignement operaters ADD\n",b)

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [ ]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
c =a+b
print(b.dtype.name,"Data type\n")
print("Add of two arrays\n",c)
c

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [ ]:
a = np.random.random((2,3))
print(a.sum(),"Sum of number")
print(a.min(),"Find the min")
print(a.max(),"Max of from array")

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [ ]:
b = np.arange(12).reshape(3,4)
print(b.sum(axis=0) ,"# sum of each column")
print(b.min(axis=1) ,"# min of each row")
print(b.cumsum(axis=1),"# cumulative sum along each row")

###  Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.
* all, 
* any, 
* apply_along_axis, 
* argmax, 
* argmin, 
* argsort, 
* average, 
* bincount, 
* ceil, 
* clip, 
* conj, 
* corrcoef, 
* cov, 
* cross, 
* cumprod, 
* cumsum, 
* diff, 
* dot, 
* floor, 
* inner, 
* inv, 
* lexsort, 
* max, 
* maximum, 
* mean, 
* median, 
* min, 
* minimum, 
* nonzero, 
* outer, 
* prod, 
* re, 
* round, 
* sort, 
* std, 
* sum, 
* trace, 
* transpose, 
* var, 
* vdot, 
* vectorize, 
* where

In [ ]:
B = np.arange(3)
C = np.arange(3)
print(np.exp(B),"Exp of Array")
print(np.sqrt(B),"Square root of a array")
print(np.add(B, C),"Addition of Two Arrays")


#### Numpy all and any 
Test whether all array elements along a given axis evaluate to True.

Test whether any array element along a given axis evaluates to True.

Returns single boolean unless axis is not None

In [ ]:
# Test whether all array elements along a given axis evaluate to True.
print(np.all([[True,False],[True,True]]))
print(np.any([[True, False], [True, True]]))
np.any(np.nan)

#### numpy.apply_along_axis

Apply a function to 1-D slices along the given axis.

Execute func1d(a, *args) where func1d operates on 1-D arrays and a is a 1-D slice of arr along axis.

In [ ]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(np.diag, -1, b)

####  argmax, argmin, argsort,
Returns the indices of the maximum values along an axis.

Returns the indices of the minimum values along an axis.

Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

In [ ]:
a = np.arange(6).reshape(2,3) + 10
print(a, "Print all a array  values\n")
print("Index of 'max of a' values:  ",np.argmax(a) )
print("Index of 'max of a' values with axis zero:  ",np.argmax(a, axis=0))
print("Index of 'max of a' values with axis one:  ",np.argmax(a, axis=1))
# axis 2 is out of bounds for array of dimension 2
#print("Index of 'max of a' values with axis zero:  ",np.argmax(a, axis=2))

In [ ]:
a = np.arange(6).reshape(2,3) + 10
print("Index of 'min of a' values:  ",np.argmin(a) )
print("Index of 'min of a' values with axis zero:  ",np.argmin(a, axis=0))
print("Index of 'min of a' values with axis one:  ",np.argmin(a, axis=1))

In [ ]:
x = np.array([3, 1, 2])
print(np.argsort(x),"Arg Sorting of a number\n")
print(np.argsort(x, axis=0) ,"# sorts along first axis (down)\n")
x = np.array([[0, 3], [2, 2]])
print(np.argsort(x, axis=1) ,"# sorts along last axis (across)\n")

### Average

Compute the weighted average along the specified axis.

In [ ]:
data = range(1,5)
print(np.average(data))
c =np.average(range(1,11), weights=range(10,0,-1))
print(c)


### bincount

Count number of occurrences of each value in array of non-negative ints.

The number of bins (of size 1) is one larger than the largest value in x. If minlength is specified, there will be at least this number of bins in the output array (though it will be longer if necessary, depending on the contents of x). Each bin gives the number of occurrences of its index value in x. If weights is specified the input array is weighted by it, i.e. if a value n is found at position i, out[n] += weight[i] instead of out[n] += 1.

In [ ]:
a = np.bincount(np.arange(5))
b = np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))
print(a,"\n","\n",b)

#### Ceil
Return the ceiling of the input, element-wise.

The ceil of the scalar x is the smallest integer i, such that i >= x. It is often denoted as \lceil x \rceil.

In [ ]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
print(np.ceil(a))

#### Clip
Clip (limit) the values in an array.

Given an interval, values outside the interval are clipped to the interval edges. For example, if an interval of [0, 1] is specified, values smaller than 0 become 0, and values larger than 1 become 1.

In [ ]:
a = np.arange(10)
np.clip(a, 1, 8)

In [ ]:
np.clip(a, 3, 6, out=a)

#### numpy.conj
Return the complex conjugate, element-wise.

The complex conjugate of a complex number is obtained by changing the sign of its imaginary part.

In [ ]:
np.conjugate(1+2j)

In [ ]:
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

#### correlation coefficients
Return Pearson product-moment correlation coefficients.

Please refer to the documentation for cov for more detail. The relationship between the correlation coefficient matrix, R, and the covariance matrix, C, is

In [3]:
np.corrcoef(x)

NameError: name 'x' is not defined

#### Cross Product
Return the cross product of two (arrays of) vectors.

The cross product of a and b in R^3 is a vector perpendicular to both a and b. If a and b are arrays of vectors, the vectors are defined by the last axis of a and b by default, and these axes can have dimensions 2 or 3. Where the dimension of either a or b is 2, the third component of the input vector is assumed to be zero and the cross product calculated accordingly. In cases where both input vectors have dimension 2, the z-component of the cross product is returned.

In [5]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [7]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

#### cumulative product 
Return the cumulative product of elements along a given axis.

In [9]:
a = np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, dtype=float)

array([  1.,   2.,   6.,  24., 120., 720.])

#### numpy.cumsum
Return the cumulative sum of the elements along a given axis.

In [13]:
a = np.array([[1,2,3], [4,5,6]])
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [15]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [17]:
np.cumsum(a,axis=0) 

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

##### numpy.diff
numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
    
Calculate the n-th discrete difference along the given axis.

The first difference is given by out[n] = a[n+1] - a[n] along the given axis, higher differences are calculated by using diff recursively.



In [20]:
u8_arr = np.array([1, 0], dtype=np.uint8)
np.diff(u8_arr)

array([255], dtype=uint8)

In [26]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

#### Dot product
Dot product of two arrays. Specifically,

If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

In [25]:
np.dot(3, 4)

12

In [30]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a,b)

array([[4, 1],
       [2, 2]])

#### numpy.floor
Return the floor of the input, element-wise.

The floor of the scalar x is the largest integer i, such that i <= x. It is often denoted as \lfloor x \rfloor.

In [35]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

#### numpy.inner
Inner product of two arrays.

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

In [41]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [43]:
a = np.arange(24).reshape((2,3,4))
>>> b = np.arange(4)
>>> np.inner(a, b)

array([[ 14,  38,  62],
       [ 86, 110, 134]])

In [46]:
#### numpy.lexsort
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

#### numpy.maximum
Element-wise maximum of array elements.

Compare two arrays and returns a new array containing the element-wise maxima. If one of the elements being compared is a NaN, then that element is returned. If both elements are NaNs then the first is returned. The latter distinction is important for complex NaNs, which are defined as at least one of the real or imaginary parts being a NaN. The net effect is that NaNs are propagated.

In [49]:
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [51]:
np.maximum(np.eye(2), [0.5, 2]) # broadcasting

array([[1. , 2. ],
       [0.5, 2. ]])

#### numpy.mean
Compute the arithmetic mean along the specified axis.


Returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. float64 intermediate and return values are used for integer inputs.

In [53]:
a = np.array([[1, 2], [3, 4]])

#### numpy.median
Compute the median along the specified axis.

Returns the median of the array elements.

In [57]:
a = np.array([[10, 7, 4], [3, 2, 1]])
np.median(a)

3.5

In [59]:
np.median(a, axis=0)

array([6.5, 4.5, 2.5])

In [61]:
np.median(a, axis=1)

array([7., 2.])

#### numpy.minimum

Element-wise minimum of array elements.

Compare two arrays and returns a new array containing the element-wise minima. If one of the elements being compared is a NaN, then that element is returned. If both elements are NaNs then the first is returned. The latter distinction is important for complex NaNs, which are defined as at least one of the real or imaginary parts being a NaN. The net effect is that NaNs are propagated.

In [63]:
np.minimum([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [65]:
np.minimum(np.eye(2), [0.5, 2])

array([[0.5, 0. ],
       [0. , 1. ]])

#### numpy.nonzero
Return the indices of the elements that are non-zero.

Returns a tuple of arrays, one for each dimension of a, containing the indices of the non-zero elements in that dimension. The values in a are always tested and returned in row-major, C-style order. The corresponding non-zero values can be obtained with:

In [67]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

##### numpy.outer

Compute the outer product of two vectors.

Given two vectors, a = [a0, a1, ..., aM] and b = [b0, b1, ..., bN], the outer product [1] is:

In [73]:
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### numpy.prod

Return the product of array elements over a given axis.

In [75]:
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x) 

16

In [77]:
x = np.array([1, 2, 3], dtype=np.uint8)
np.prod(x).dtype == np.uint

True

#### sort
Return a sorted copy of an array.

In [79]:
>>> a = np.array([[1,4],[3,1]])
>>> np.sort(a)   

array([[1, 4],
       [1, 3]])

#### standard deviation
Compute the standard deviation along the specified axis.

Returns the standard deviation, a measure of the spread of a distribution, of the array elements. The standard deviation is computed for the flattened array by default, otherwise over the specified axis.

In [81]:
a = np.array([[1, 2], [3, 4]])
>>> np.std(a)

1.118033988749895

In [83]:
np.std(a, axis=0)

array([1., 1.])

#### numpy.sum
Sum of array elements over a given axis.

In [85]:
np.sum([0.5, 1.5])

2.0

#### numpy.trace

Return the sum along diagonals of the array.

If a is 2-D, the sum along its diagonal with the given offset is returned, i.e., the sum of elements a[i,i+offset] for all i.

If a has more than two dimensions, then the axes specified by axis1 and axis2 are used to determine the 2-D sub-arrays whose traces are returned. The shape of the resulting array is the same as that of a with axis1 and axis2 removed.

In [87]:
np.trace(np.eye(3))

3.0

#### numpy.transpose

Permute the dimensions of an array.

In [91]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [93]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

#### numpy.var

Compute the variance along the specified axis.

Returns the variance of the array elements, a measure of the spread of a distribution. The variance is computed for the flattened array by default, otherwise over the specified axis.

In [99]:
a = np.array([[1, 2], [3, 4]])
print(np.var(a),"\n")
print(np.var(a, axis=0),"\n")

print(np.var(a, axis=1),"\n")

1.25 

[1. 1.] 

[0.25 0.25] 



#### numpy.vdot(a, b)
Return the dot product of two vectors.

The vdot(a, b) function handles complex numbers differently than dot(a, b). If the first argument is complex the complex conjugate of the first argument is used for the calculation of the dot product.

Note that vdot handles multidimensional arrays differently than dot: it does not perform a matrix product, but flattens input arguments to 1-D vectors first. Consequently, it should only be used for vectors.

In [102]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

#### numpy.vectorize

Generalized function class.

Define a vectorized function which takes a nested sequence of objects or numpy arrays as inputs and returns a single numpy array or a tuple of numpy arrays. The vectorized function evaluates pyfunc over successive tuples of the input arrays like the python map function, except it uses the broadcasting rules of numpy.

The data type of the output of vectorized is determined by calling the function with the first element of the input. This can be avoided by specifying the otypes argument.

In [105]:
def myfunc(a, b):
...     "Return a-b if a>b, otherwise return a+b"
...     if a > b:
...         return a - b
...     else:
...         return a + b

In [109]:
vfunc = np.vectorize(myfunc)
print(vfunc.__doc__)
vfunc([1, 2, 3, 4], 2)

Return a-b if a>b, otherwise return a+b


array([3, 4, 1, 2])

##### numpy.where
numpy.where(condition[, x, y])


Return elements chosen from x or y depending on condition.

In [112]:
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])