##### One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [3]:
import numpy as np

In [6]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [8]:
a[0]

0

In [11]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [13]:
a[ : :-1] 

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [15]:
for i in a:
...     print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


###### Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [18]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [20]:
 b[2,3]

23

In [22]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [24]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [27]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [29]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

##### Iterating over multidimensional arrays is done with respect to the first axis:

In [30]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
