When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

In [3]:
import numpy as np

#### No Copy at All
Simple assignments make no copy of array objects or of their data.

In [7]:
a = np.arange(12)
b = a            # no new object is created    
b is a           # a and b are two names for the same ndarray object

True

In [9]:
b.shape = 3,4    # changes the shape of a

#### View or Shallow Copy

In [19]:
c = a.view()
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
c is a

False

In [16]:
c.base is a # c is a view of the data owned by a

True

In [22]:
a.shape
c[0,3] = 1234   # a's data changes
c

array([[   0,    1,    2, 1234],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [24]:
s = a[ : , 1:3] # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10  # s[:] is a view of s. Note the difference between s=10 and s[:]=10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

#### Deep Copy
The copy method makes a complete copy of the array and its data.

In [27]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [29]:
d.base is a                           # d doesn't share anything with a

False

In [31]:
d[0,0] = 9999
d

array([[9999,   10,   10, 1234],
       [   4,   10,   10,    7],
       [   8,   10,   10,   11]])

## Functions and Methods Overview
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

#### Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
#### Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
#### Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
#### Questions
all, any, nonzero, where
#### Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
#### Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
#### Basic Statistics
cov, mean, std, var
#### Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot