#### Linear Algebra
Work in progress. Basic linear algebra to be included here.

#### Simple Array Operations

In [2]:
import numpy as np

In [4]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [6]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [8]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"
u

array([[1., 0.],
       [0., 1.]])

In [13]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j @ j        # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

In [15]:
np.trace(u)  # trace

2.0

In [18]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [19]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))